spring:
  datasource:
    initialization-mode: always
    schema: schema.sql
    data: data.sql
    url: jdbc:h2:mem:testdb
    #    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true
