server:
  port: 8080
spring:
  datasource:
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:mem:testdb
    #    url: jdbc:h2:tcp://localhost/~/test
    username: sa
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

