spring:
  data:
    mongodb:
      #      port: 27017
      database: homework08
      #      uri: mongodb://172.17.0.2:27017
      host: 172.17.0.2
      port: 27017
#  datasource:
#    initialization-mode: always
#    schema: schema.sql
#    data: data.sql
#    url: jdbc:h2:mem:testdb
#    #    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#  jpa:
#    #    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#
#    properties:
#      hibernate:
#        format_sql: true
#
#    show-sql: true
mongock:
  change-logs-scan-package: ru.otus.homework08.mongock.changelog
